### ISSUE TITLE
Ask me anything 페이지 → Github REST API vs (Create Issue) 구현

### ISSUE THREAD

**Issue by tooget** [tooget/tooget.github.io#4]
## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.

Ask me anything 페이지에서 입력받은 내용으로 https://github.com/tooget/tooget.github.io 의 이슈가 생성되도록 합니다.

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.

해당 Github REST API / POST(Create Issue) 를 위한 API가 구현되어 있지 않습니다.

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.

@tooget 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.
  - [x] 컴포넌트 내 스크립트 구현
  - [x] 로컬에서 이슈 생성 확인
    - [x] label 적용
    - [x] 타이틀 적용
    - [x] 본문 Markdown 적용
  - [ ] Github Pages 상 이슈 생성 확인
  - [ ] Github Actions - secrets 적용

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우는 **반드시 이슈 번호를 적어주세요**
  - 관련이슈: #3 
  - 참고사항
    - Github Oauth
    - Github Personal Access Token

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)
  - 예상소요시간: **1W-**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)
  - Reporter: @tooget 
  - Domain  : **UX**
  - Priority: **Medium**
  - Task    : **Enhancement**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.
  - 예상수익: 0 원/월
  - 예상비용: 0 원/월

**Comment by tooget** [comment]
## baarer + PAT 토큰으로 API 호출시 토큰이 사라진다!
![Screen Shot 2021-09-01 at 22 01 46](https://user-images.githubusercontent.com/24958726/131675952-8b559201-8e21-4601-a5ec-74345529d5ac.png)

## [GitHub] OAuth access token found in commit
```
Hello tooget,

We noticed that a valid OAuth, GitHub App or Personal Access Token of yours was committed to a GitHub repository. Disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data.

As a precautionary measure, we have revoked the token. You will need to generate a new token for the app to authenticate to GitHub.

Here are a couple of steps you can do to ensure your account security has not been compromised:

* Review any unauthorized applications, and remove any you don’t recognize:
https://docs.github.com/articles/reviewing-your-authorized-integrations/#reviewing-your-authorized-oauth-apps
https://docs.github.com/articles/reviewing-your-authorized-integrations/#reviewing-your-authorized-github-apps

* Review your security log to ensure that no malicious activity has occurred: https://docs.github.com/articles/reviewing-your-security-log/

The commit in question is at https://github.com/tooget/tooget.github.io/blob/875d632e7ae93783f3fd688b7e05978f69b0b79b/components/AskingInputForm.vue
```

**Comment by tooget** [comment]
## 로컬 동작 확인
![Screen Shot 2021-09-01 at 22 05 00](https://user-images.githubusercontent.com/24958726/131676338-cddfd131-c477-4b58-96c4-9999db101c1c.png)
![Screen Shot 2021-09-01 at 22 05 39](https://user-images.githubusercontent.com/24958726/131676387-e3216810-808f-4aa8-b707-1d3568205c4b.png)

**Comment by tooget** [comment]
## 참고: 토큰 감추기? 

https://gist.github.com/derzorngottes/3b57edc1f996dddcab25

**Comment by tooget** [comment]
## Github Apps 인증 API를 구현하는 것으로 하겠음
 - 사유: 정신건강

## Github Apps 토큰 생성 및 인증에 필요한 요소
 - 퍼블릭키 (PEM 파일)
 - 퍼블릭키를 사용하는 JWT 생성 서버

**Comment by tooget** [comment]
## 구현대상: JWT 서버
 - 레퍼런스
    - 공식: https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-a-github-app
    - https://www.altostra.com/blog/single-github-app-for-multiple-accounts
 - API 구성: GCP ~~해보고 싶음~~
    - Serverless: Google Cloud Functions API
       - 필연적으로 Build API 활성화 필요
       - 레퍼런스: https://codelabs.developers.google.com/codelabs/cloud-functions-python-http#2
    - Secrets(Github Apps PEM file): Google Cloud Secrets API
       - 레퍼런스: https://www.asobou.co.jp/blog/web/secret-manager

**Comment by tooget** [comment]
## Google Cloud Functions API 에러
```
2021-09-07T15:01:58.654Zjwt-creation-app-for-tooget-github-ioog1c99uev2pb Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 5, in jwt from jwt.contrib.algorithms.pycrypto import RSAAlgorithm File "/env/local/lib/python3.7/site-packages/jwt/contrib/algorithms/pycrypto.py", line 1, in <module> import Crypto.Hash.SHA256 ModuleNotFoundError: No module named 'Crypto'
Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 5, in jwt from jwt.contrib.algorithms.pycrypto import RSAAlgorithm File "/env/local/lib/python3.7/site-packages/jwt/contrib/algorithms/pycrypto.py", line 1, in <module> import Crypto.Hash.SHA256 ModuleNotFoundError: No module named 'Crypto'
```

## 해결: `requirements.txt`에 `pycrypto==2.6.1` 추가
 - 레퍼런스: https://stackoverflow.com/questions/29350204/app-engine-importerror-no-module-named-crypto-hash

**Comment by tooget** [comment]
## Github Apps API 및 CORS 레퍼런스
 - https://gist.github.com/pelson/47c0c89a3522ed8da5cc305afc2562b0
 - https://qiita.com/att55/items/2154a8aad8bf1409db2b
 - https://cloud.google.com/functions/docs/writing/http#functions_http_cors-python

**Comment by tooget** [comment]
```sh
curl -i -X POST \
-H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MzExODcwMjAsImV4cCI6MTYzMTE4NzY4MCwiaXNzIjoxMzYzNDJ9.mSJ5yVjJBEt0EaajM-n4oyWW0_UOZkyytJpOntbKAaeJ8yxObS_RLu0r52NIGkB9LeEynknSPK3igiA2UHvMrA0iZ9dxWWAhvTdDxTa-YOOagbaNDq9EVUer3L65YlU9e-bcmFTWRl1wrqEI6tK5mIVQ18E-2groxLETzeOzq5WfA0XpxmKn6giC_7AEzPIrjqFFoYyLZJ-2Dac34qSICliOSNwZ7HPXKImKLtty1ldZCEJ0LTgxwgWj4CooysFwes7ICiIr_ziYGav-X71z6DFZQOziVYHFqF5yqKmUORolwFWK1z9WYYZd502g3VbOD2nebE-RfumBX9ZMdRgJgQ" \
-H "Accept: application/vnd.github.v3+json" \
https://api.github.com/app/installations/19295983/access_tokens
```
